package com.businessos.auth.role.enums;

public enum PermissionCode {
    // COMPANY
    COMPANY_VIEW,
    COMPANY_UPDATE,
    COMPANY_SETTINGS,
    COMPANY_BRANDING,

    // USER
    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    // EMPLOYEE
    EMPLOYEE_VIEW,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    // DEPARTMENT
    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    // DESIGNATION
    DESIGNATION_VIEW,
    DESIGNATION_CREATE,
    DESIGNATION_UPDATE,
    DESIGNATION_DELETE,

    // LEAVE
    LEAVE_VIEW,
    LEAVE_CREATE,
    LEAVE_UPDATE,
    LEAVE_CANCEL,
    LEAVE_APPROVE,
    LEAVE_REJECT,

    // EXPENSE
    EXPENSE_VIEW,
    EXPENSE_CREATE,
    EXPENSE_UPDATE,
    EXPENSE_DELETE,
    EXPENSE_APPROVE,
    EXPENSE_REJECT,

    // ATTENDANCE
    ATTENDANCE_VIEW,
    ATTENDANCE_MARK,
    ATTENDANCE_UPDATE,
    ATTENDANCE_APPROVE,

    // BIOMETRIC
    BIOMETRIC_VIEW,
    BIOMETRIC_MANAGE,

    // PAYROLL
    PAYROLL_VIEW,
    PAYROLL_PROCESS,
    PAYROLL_APPROVE,

    // SERVICE REQUEST
    SERVICE_REQUEST_VIEW,
    SERVICE_REQUEST_CREATE,
    SERVICE_REQUEST_ASSIGN,
    SERVICE_REQUEST_APPROVE,
    SERVICE_REQUEST_CLOSE,

    // CLIENT
    CLIENT_VIEW,
    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_DELETE,

    // INVOICE
    INVOICE_VIEW,
    INVOICE_CREATE,
    INVOICE_UPDATE,
    INVOICE_DELETE,
    INVOICE_SEND,
    INVOICE_PAYMENT,
    INVOICE_CANCEL,

    // JOURNAL ENTRY
    JOURNAL_ENTRY_VIEW,
    JOURNAL_ENTRY_CREATE,
    JOURNAL_ENTRY_APPROVE,
    JOURNAL_ENTRY_POST,
    JOURNAL_ENTRY_DELETE,

    // CHART OF ACCOUNTS
    CHART_OF_ACCOUNT_VIEW,
    CHART_OF_ACCOUNT_CREATE,
    CHART_OF_ACCOUNT_UPDATE,
    CHART_OF_ACCOUNT_DELETE,

    // GENERAL LEDGER
    GENERAL_LEDGER_VIEW,
    GENERAL_LEDGER_RECONCILE,

    // BANK RECONCILIATION
    BANK_RECONCILIATION_VIEW,
    BANK_RECONCILIATION_CREATE,
    BANK_RECONCILIATION_RECONCILE,

    // PAYMENT RECEIPT
    PAYMENT_RECEIPT_VIEW,
    PAYMENT_RECEIPT_CREATE,
    PAYMENT_RECEIPT_CONFIRM,
    PAYMENT_RECEIPT_DELETE,

    // FINANCIAL REPORTS
    FINANCIAL_REPORT_VIEW,

    // SOFTWARE LICENSE
    SOFTWARE_LICENSE_VIEW,
    SOFTWARE_LICENSE_CREATE,
    SOFTWARE_LICENSE_UPDATE,
    SOFTWARE_LICENSE_DELETE,
    SOFTWARE_LICENSE_ASSIGN,

    // OFFBOARDING
    OFFBOARDING_VIEW,
    OFFBOARDING_CREATE,
    OFFBOARDING_MANAGE,
    OFFBOARDING_DELETE,

    // AI
    AI_CHAT,
    AI_ADMIN
}
