package com.businessos.auth.role.enums;

public enum PermissionCode {
    // COMPANY
    COMPANY_VIEW,
    COMPANY_UPDATE,
    COMPANY_SETTINGS,
    COMPANY_BRANDING,

    // USER
    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    // EMPLOYEE
    EMPLOYEE_VIEW,
    EMPLOYEE_CREATE,
    EMPLOYEE_UPDATE,
    EMPLOYEE_DELETE,

    // DEPARTMENT
    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    // DESIGNATION
    DESIGNATION_VIEW,
    DESIGNATION_CREATE,
    DESIGNATION_UPDATE,
    DESIGNATION_DELETE,

    // LEAVE
    LEAVE_VIEW,
    LEAVE_CREATE,
    LEAVE_UPDATE,
    LEAVE_CANCEL,
    LEAVE_APPROVE,
    LEAVE_REJECT,

    // EXPENSE
    EXPENSE_VIEW,
    EXPENSE_CREATE,
    EXPENSE_UPDATE,
    EXPENSE_DELETE,
    EXPENSE_APPROVE,
    EXPENSE_REJECT,

    // ATTENDANCE
    ATTENDANCE_VIEW,
    ATTENDANCE_MARK,
    ATTENDANCE_UPDATE,

    // PAYROLL
    PAYROLL_VIEW,
    PAYROLL_PROCESS,
    PAYROLL_APPROVE,

    // SERVICE REQUEST
    SERVICE_REQUEST_VIEW,
    SERVICE_REQUEST_CREATE,
    SERVICE_REQUEST_ASSIGN,
    SERVICE_REQUEST_APPROVE,
    SERVICE_REQUEST_CLOSE,

    // CLIENT
    CLIENT_VIEW,
    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_DELETE,

    // AI
    AI_CHAT,
    AI_ADMIN
}
