package com.businessos.modules.ai.enums;

public enum AiFeature {
    EMPLOYMENT_LETTER,
    LEAVE_POLICY,
    PERFORMANCE_REVIEW,
    CRM_LEAD_SUMMARY,
    CRM_ACTIVITY_SUMMARY,
    INVOICE_SUMMARY,
    SERVICE_REQUEST_SUMMARY,
    ANNOUNCEMENT_DRAFT,
    HOLIDAY_DRAFT,
    WORKFLOW_SUGGESTION,
    SEARCH_ANSWER,
    BUSINESS_INSIGHTS,
    GENERAL
}
